name: NyxxMetin2
version: 1.0
main: nyxx.nyxxMetin2.NyxxMetin2
api-version: '1.21'
author: Nyxx
description: Profesyonel Hardcore Metin2 Demirci Sistemi.

commands:
  demirci:
    description: Demirci menüsünü açar.
    permission: nyxxmetin2.player
  nyxxadmin:
    description: Plugin yönetim komutu.
    permission: nyxxmetin2.admin

permissions:
  nyxxmetin2.player:
    default: true
  nyxxmetin2.admin:
    default: op